language: 'node_js'
node_js: '0.10'

before_install:
  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports
  - sudo apt-get update

install:
  - sudo apt-get install libcv-dev libcvaux-dev libhighgui-dev libopencv-dev
  - npm install

before_script: 'if [[ "$TRAVIS_BRANCH" != "master" ]]; then npm install git://github.com/hybridgroup/cylon.git#dev; fi'

script: 'make'
