language: node_js
node_js: '0.10'
before_install:
  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports
  - sudo apt-get update
install:
  - sudo apt-get install libcv-dev libcvaux-dev libhighgui-dev libopencv-dev
  - npm install
  - npm install git://github.com/hybridgroup/cylon.git
  - npm install -g istanbul codeclimate-test-reporter
script:
  - make ci
  - CODECLIMATE_REPO_TOKEN=4491d8f5ab0c54cb98fba95b78bc4fede70d953bf5c420b81f964fd3f85fd9a5 codeclimate < coverage/lcov.info
